# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andrew Flack
tagline:          The Personal Website of Andrew Flack
url:              andrewflack.github.io
paginate:         1
baseurl:          /
author:
  name:           Andrew Flack
  url:            https://twitter.com/andrew_flack
  email:          flack.andrew@gmail.com
disqus_shortname: andrewflackgithubio

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/andrewflack/andrewflack.github.io
  
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
