# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            andrew
tagline:          'A Jekyll theme'
description:      'Blah blah blah <a href="http://jekyllrb.com" target="_blank">Jekyll</a> blah blah'
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
