# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Andrew
tagline:          'The personal website of Andrew Flack'
description:      
url:              

author:
  name:           'Andrew Flack'
  url:            https://twitter.com/andrew_flack

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/andrewflack/andrewflack.github.io
  
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
