baseurl = "/"
languageCode = "en-us"
title = "Andrew Flack"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-108088384-1"
disqusShortname = "@flack_andrew"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/andrewflack"

[params]
    description = "Personal website of Andrew Flack"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "IMG_4352.png"
    width = 50
    height = 50
    alt = "Logo"

